//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalGame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnimalGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 076666667666666292
        ///066666666666667050
        ///000000000000000010
        ///031111111111111110
        ///000000001000000000
        ///066666601066666660
        ///066666601066766660
        ///066676601066666760
        ///222222231222222222
        ///000000001000000000
        ///011111111111111140
        ///080000000000000000.
        /// </summary>
        internal static string Stage1 {
            get {
                return ResourceManager.GetString("Stage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 292222222222222222
        ///252066766666660000
        ///010066666676660406
        ///010066666666660106
        ///010000000000000106
        ///011111111111111107
        ///000000000000000106
        ///066766666666760106
        ///066666676666660100
        ///222222222222222522
        ///001111111111111113
        ///008000000000000000.
        /// </summary>
        internal static string Stage2 {
            get {
                return ResourceManager.GetString("Stage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 222222222222222222
        ///200000000000000002
        ///201111111111111158
        ///201430000000000002
        ///221222222222222222
        ///205000000000000002
        ///201111111111111102
        ///200000000000034102
        ///222222222222222522
        ///000000000000000100
        ///011111111111111100
        ///094300000000000000.
        /// </summary>
        internal static string Stage3 {
            get {
                return ResourceManager.GetString("Stage3", resourceCulture);
            }
        }
    }
}
